name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: |
          node -v
          npm install --global lix
          lix install haxe 4.3.0 --global
          lix download
          npm ci
          haxelib install tests.hxml --always

      - name: Test
        run: |
          haxe tests.hxml
