---
name: 'Upstream Sync'

on:
  schedule:
      # scheduled at 21:00 UTC every friday
    - cron: '0 21 * * 5'

  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-22.04
    name: Sync latest commits from upstream repo

    steps:
    # REQUIRED step
    # Step 1: run a standard checkout action, provided by github
    - name: Checkout target repo
      id: checkout
      uses: actions/checkout@v4

    # REQUIRED step
    # Step 2: run the sync action
    - name: Sync upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      with:
        target_sync_branch: master
        # REQUIRED 'target_repo_token' exactly like this!
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_branch: master
        upstream_sync_repo: RblSb/SyncTube

        # Set test_mode true to run tests instead of the true action!!
        test_mode: false
      
    # Step 3: Display a sample message based on the sync output var 'has_new_commits'
    - name: New commits found
      if: steps.sync.outputs.has_new_commits == 'true'
      run: echo "New commits were found to sync."
    
    - name: No new commits
      if: steps.sync.outputs.has_new_commits == 'false'
      run: echo "There were no new commits."
